export * from "./integralAffines";
export * from "./integralTrinomials";
export * from "./integralKCosinus";
export * from "./integralKSinus";
//export * from "./integralFractions";
export * from "./integralExpU";
export * from "./integralExpAxPlusB";
export * from "./integralDerivatedUSinU";
export * from "./integralDerivatedUCosU";
