export * from "./areas";
export * from "./cartesian";
export * from "./perimeters";
export * from "./pythagore";
export * from "./thales";
export * from "./vectors";
export * from "./convexity";
export * from "./volumes";
// export * from "./triangles";
export * from "./euclidianConstructions";
export * from "./shapes";
// export * from "./euclidian";
