export * from "./chemicalEquations";
export * from "./chemicalReactionsProduct";
export * from "./delution";
export * from "./formulaFromComposition";
export * from "./kineticEnergy";
export * from "./molarQuantity";
export * from "./moleculeFormula";
export * from "./moleculeNomenclature";
export * from "./pH";
export * from "./perceivedFrequency";
export * from "./potentialEnergy";
export * from "./snellDescartes";
export * from "./sound";
export * from "./math";
export * from "./weight";
export * from "./forces";
export * from "./waves";
export * from "./chemicalElements";
export * from "./chemicalReactions";
export * from "./mole";
export * from "./mecanicalWaves";
export * from "./fluids";
export * from "./electricity";
export * from "./calibrationCurveOfSolution";
export * from "./dosage";
export * from "./spectral";
export * from "./energy";

/**exos pris des maths */
export * from "../math/percent/findProportion";
export * from "../math/calcul/proportionality/proportionalityTable";
export { powersOfTenDivision } from "../math/powers/powersDivision";
export * from "../math/powers/decimalToScientific";
export * from "../math/calcul/mentalCaluls/mentalAddAndSub";
export { log10PowerSimplifying } from "../math/functions/logarithm/log10PowerSimplifying";
export { log10SumSimplifying } from "../math/functions/logarithm/log10Simplifying";
export { log10PowerEquation } from "../math/functions/logarithm/logPowerEquation";
export * from "../math/calculLitteral/equation/equationType1Exercise";
export * from "../math/calculLitteral/equation/equationType2Exercise";
export * from "../math/calculLitteral/equation/equationType3Exercise";
export * from "../math/calculLitteral/equation/equationType4Exercise";
export * from "../math/geometry/vectors/scalarProductViaCoords";
export * from "../math/geometry/vectors/scalarProductViaCos";
export * from "../math/geometry/vectors/coordinatesReading";
export * from "../math/functions/affines/affineExpressionReading";
export * from "../math/geometry/thales/thales";
export * from "../math/geometry/thales/thalesCalcul";
export * from "../math/equaDiff/equaDiffCheckSolutionFirstOrder";
export * from "../math/equaDiff/equaDiffGeneralForme";
export * from "../math/equaDiff/equaDiffGeneralFormeWithIC";
export * from "../math/derivation/derivativeNumberReading";
export * from "../math/derivation/derivative/usualderivative";
export { thirdDegreeDerivative } from "../math/derivation/derivative/thirdDegreeDerivative";
export { firstDegreeDerivative } from "../math/derivation/derivative/firstDegreeDerivative";
export { secondDegreeDerivative } from "../math/derivation/derivative/secondDegreeDerivative";
export * from "../math/trigonometry/trigonometrySideCalcul";
export * from "../math/trigonometry/trigonometryAngleCalcul";
