import { addAndSubExercise } from "./exercises/calcul/addAndSub";
import { allIdentities } from "./exercises/calculLitteral/distributivity/allIdentities";
import { doubleDistributivity } from "./exercises/calculLitteral/distributivity/doubleDistributivity";
import { simpleDistributivity } from "./exercises/calculLitteral/distributivity/simpleDistributivity";
import { equationType1Exercise } from "./exercises/calculLitteral/equation/equationType1Exercise";
import { equationType2Exercise } from "./exercises/calculLitteral/equation/equationType2Exercise";
import { equationType3Exercise } from "./exercises/calculLitteral/equation/equationType3Exercise";
import { equationType4Exercise } from "./exercises/calculLitteral/equation/equationType4Exercise";
import { factoType1Exercise } from "./exercises/calculLitteral/factorisation/factoType1Exercise";
import { simplifySquareRoot } from "./exercises/squareRoots/simpifySquareRoot";
import { randint } from "./mathutils/random/randint";
import { Rational } from "./numbers/rationals/rational";
import { SquareRoot } from "./numbers/reals/squareRoot";
import { Affine } from "./polynomials/affine";
import { Polynomial } from "./polynomials/polynomial";
import { latexParse } from "./tree/latexParser/latexParse";
import { VariableNode } from "./tree/nodes/variables/variableNode";

console.log(equationType1Exercise.generator(10));
console.log(equationType2Exercise.generator(10));
console.log(equationType3Exercise.generator(10));
console.log(equationType4Exercise.generator(10));
